language: go
go:
    - 1.2

before_install:
    - go get code.google.com/p/go.tools/cmd/cover
    - go get github.com/tools/godep
    - export PATH=$HOME/gopath/bin:$PATH

install: godep restore

script:
    - godep go test -cover ./...
